apiVersion: apps/v1
kind: Deployment
metadata:
  name: frgdswd10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frgdswd10
  template:
    metadata:
      labels:
        app: frgdswd10
    spec:
      containers:
      - image: okteto.dev/frgdswd10:latest
        name: frgdswd10
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ad6896de-cf28-462e-a7c6-4fc31b805475a"
        - name: Vless_Path
          value: "/vl55dfer5"
        - name: Vmess_UUID
          value: "ad6896de-cf28-462e-a7c6-4fc31b805475"
        - name: Vmess_Path
          value: "/vm66ert6"
        - name: Share_Path
          value: "/v2link"
